### PR TITLE
Add Kodi, PHPStorm-alt, Transmission and fix AI icns

### PR DESCRIPTION
**Pull request by gilbarbara**

### CODE REVIEW

**Comment by tinalatif** [comment]
Ah! I see what happened. An update to Adobe Acrobat accidentally overrode the Illustrator .icns instead of the Acrobat one. Thanks for catching that.

Also I think you're missing the .ai for the 2nd Kodi version

**Comment by gilbarbara** [comment]
I added the Kodi all version in the same file as a second artboard.. I'll push them as separate files

**Comment by tinalatif** [comment]
Ah gotcha, I didn't open the .ai files. I think it's best to have them as separate files for completeness. Give me a heads up when you pushed it

**Comment by gilbarbara** [comment]
Done!

**Comment by tinalatif** [comment]
Cool, thanks!

**Pull request merged**
