### PR TITLE
Add Toggl Desktop App

### PR DESCRIPTION
**Pull request by coltonfitzgerald**

### CODE REVIEW

**Comment by wjramos** [comment]
I like it, any chance you could add the .ai and a .icns version? Also, a grey version for "stopped" status would be really useful

**Comment by coltonfitzgerald** [comment]
How are you making the .icns version? I included one in my pull request but it was generated using some sketchy online converter. I'll go ahead and make a stopped version as well.

**Comment by wjramos** [comment]
I have been using [this AI exporter script](https://github.com/choffmeister/adobe-illustrator-icnsexport) to generate the .icns copies (you have to type out the full name including the extension)

**Comment by tinalatif** [comment]
The .ai file too please! 
I've been using img2icns but that script is also a good idea

**Comment by coltonfitzgerald** [comment]
Just added a commit with .ai files, .icns files and .png files for both on and off states.

**Pull request merged**
