### PR TITLE
Added Popcorn Time and Papers

### PR DESCRIPTION
**Pull request by FreshRamen**
I’m not sure I did this right, feedback would be greatly appreciated.
Commit contains png, icns and ai vector graphic for both apps.

### CODE REVIEW

**Comment by wjramos** [comment]
I'd say you should remove the gradients from Popcorn Time, and a different background may be more flattering (I'm thinking something close to #B3E5FC).

For Papers I'd simply recommend shrinking the glyph to the size of the inner template bounding box.

**Comment by FreshRamen** [comment]
Thanks for the feedback! I'll get to it over the weekend.

**Comment by FreshRamen** [comment]
I made a new commit. Papers is resized and Popcorn Time has a somewhat more minimalistic set of colors. Also the background color is now #B3E5FC.

**Comment by mknrls** [comment]
@FreshRamen looks good :) much better

**Comment by FreshRamen** [comment]
Thanks :)

**Comment by wjramos** [comment]
@FreshRamen excellent!

**Comment by FreshRamen** [comment]
Shall I do anything else before this gets merged? I'm still not 100% sure how everything works. :)

**Pull request merged**
