### PR TITLE
Add Sketch Toolbox

### PR DESCRIPTION
**Pull request by wjramos**

### CODE REVIEW

**Comment by wjramos** [comment]
Going to revise and add a bit of depth to the box component.
Thanks @mknrls!

**Comment by mknrls** [comment]
@wjramos saw my msg here ? (just making sure)

**Comment by wjramos** [comment]
@mknrls Yes I did, I thought I responded, but I guess not. Oops! 
I'm going to try some various options to see which ends up looking best. I'll post them here for feedback.

**Comment by mknrls** [comment]
:) hype

**Comment by wjramos** [comment]
sketch-toolkit

**Comment by mknrls** [comment]
love it ;) diamond isn't center tho and fix bottom left side mistake (you will see it right away)

**Comment by wjramos** [comment]
Oops, I've been staring at it too long, updated it above

**Comment by mknrls** [comment]
Good to go :)

**Pull request closed without merging**
