### PR TITLE
Update README.md / Delete .DS_Store

### PR DESCRIPTION
**Pull request by mknrls**
* Fix text formatting for Calender app installation instructions
* Removed random .DS_Store file

### CODE REVIEW

**Comment by wjramos** [comment]
those .DS_Stores are a pain, we should probably throw in a .gitignore

**Comment by mknrls** [comment]
the funny part about it is that there is one but didn't catch it some how

**Comment by wjramos** [comment]
Yeah, pulling hasn't been creating the .gitignore for me locally either, not sure why. I just issued a pull request for an updated .gitignore which includes other potential hidden files that might try and sneak their way in

**Comment by mknrls** [comment]
good idea :+1:

**Comment by tinalatif** [comment]
woo digging the header

**Comment by mknrls** [comment]
Thank :) happy you like like.

**Comment by wjramos** [comment]
I also really like it!

**Comment by mknrls** [comment]
:D

**Pull request merged**
